stages:
  - test

test-all:
  stage: test
  image: python:3.13
  tags:
    - geocontrol
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - pytest tests/ --cov --cov-report=term
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "QA"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "QA"'
      when: always
  allow_failure: false