stages:
  - test

test-all:
  stage: test
  image: python:3.13
  tags:
    - geocontrol
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - pytest tests/ --junitxml=reports/junit/pytest-results.xml --cov --cov-report=term --cov-report=xml
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "delivery"'
      when: always
  artifacts:
    when: always
    reports:
      junit: reports/junit/pytest-results.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    expire_in: 1 week
  allow_failure: false